export const BACKEND_URL = `${process.env.NEXT_PUBLIC_BACKEND_URL}`;
export const BASE_URL = `${process.env.NEXT_PUBLIC_BASE_URL}`;
export const SITE_NAME = 'Alvacus';
export const DESCRIPTION =
  'Alvacus is the ultimate calculator creation tool for students, professionals, and anyone in need of quick math solutions. Our app allows you to easily create custom calculators using your own formulas, which can then be shared on our interactive dashboard with other users. These users can save your calculators to their profiles, try them out, and leave comments for feedback. With Alvacus, you have the power of customizable calculators at your fingertips – no downloads necessary. Try it now and see the difference for yourself.';
export const KEYWORDS = [
  'Alvacus',
  'Alvacus calculator',
  'Alvacus converter',
  'Alvacus tools',
  'calculator',
  'converter',
  'tools',
  'math',
  'mathematics',
  'physics',
  'chemistry',
  'biology',
  'science',
  'engineering',
  'technology',
  'education',
  'school',
  'college',
  'university',
  'high school',
  'middle school',
  'elementary school',
  'math calculator',
  'math converter',
  'math tools',
  'physics calculator',
  'physics converter',
  'physics tools',
  'chemistry calculator',
  'chemistry converter',
  'chemistry tools',
  'biology calculator',
  'biology converter',
  'biology tools',
  'science calculator',
  'science converter',
  'science tools',
  'engineering calculator',
  'engineering converter',
  'engineering tools',
  'technology calculator',
  'technology converter',
  'technology tools',
  'education calculator',
  'education converter',
  'education tools',
  'school calculator',
  'school converter',
  'school tools',
  'college calculator',
  'college converter',
  'college tools',
  'university calculator',
  'university converter',
  'university tools',
  'high school calculator',
  'high school converter',
  'high school tools',
  'middle school calculator',
  'middle school converter',
  'middle school tools',
  'elementary school calculator',
  'elementary school converter',
  'elementary school tools',
];
