export const BACKEND_URL = `${process.env.NEXT_PUBLIC_BACKEND_URL}`;
export const BASE_URL = `${process.env.NEXT_PUBLIC_BASE_URL}`;
export const SITE_NAME = 'Alvacus';
export const DESCRIPTION =
  'Revolutionize calculations using Alvacus: Custom-build calculators from specific formulas, enjoy seamless unit conversions, and engage with profile saving, commenting, and easy sharing. Tailored for accuracy and collaboration.';
export const KEYWORDS = [
  'Alvacus',
  'Alvacus calculator',
  'Alvacus converter',
  'Alvacus tools',
  'calculator',
  'converter',
  'tools',
  'math',
  'mathematics',
  'physics',
  'chemistry',
  'biology',
  'science',
  'engineering',
  'technology',
  'education',
  'school',
  'college',
  'university',
  'high school',
  'middle school',
  'elementary school',
  'math calculator',
  'math converter',
  'math tools',
  'physics calculator',
  'physics converter',
  'physics tools',
  'chemistry calculator',
  'chemistry converter',
  'chemistry tools',
  'biology calculator',
  'biology converter',
  'biology tools',
  'science calculator',
  'science converter',
  'science tools',
  'engineering calculator',
  'engineering converter',
  'engineering tools',
  'technology calculator',
  'technology converter',
  'technology tools',
  'education calculator',
  'education converter',
  'education tools',
  'school calculator',
  'school converter',
  'school tools',
  'college calculator',
  'college converter',
  'college tools',
  'university calculator',
  'university converter',
  'university tools',
  'high school calculator',
  'high school converter',
  'high school tools',
  'middle school calculator',
  'middle school converter',
  'middle school tools',
  'elementary school calculator',
  'elementary school converter',
  'elementary school tools',
];
